spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.244.127.184:3306/xgcd?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      exclude: WEB-INF/**
      enabled: true #open devtools
      additional-paths: src/main/java #restart path
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/static
server:
  port: 8080